### ISSUE TITLE
Bunch of JSLINT errors in Brackets that you didn't get.

### ISSUE THREAD

**Issue by robinclaes** [johnpapa/pluralsight-gulp#16]
Hi! I'm following your course. Originally, I was using WebStorm for programming, but I got a bunch of errors that you didn't get. I then switched to Brackets, but I still get these JSLint problems.

The errors look like this:
 Missing 'use strict' statement.
'log' was used before it was defined.
'require' was used before it was defined.
'module' was used before it was defined.

I've just finished "Getting started with Gulp" and it would be convenient to not get these errors, like you are.

Great course by the way! I hope you can help me.

**Comment by Spydr331** [comment]
I am having the same issue.  I ignored it for a while by keeping out the log function but when i tried to put it back in i got too many jslint errors.  variations of the same ones listed by rclaes.  I am on windows if that makes a difference.

I also have one extra error since I went a bit farther into the course. 
"Expected an identifier and instead saw 'if' (a reserved word)."

**Comment by johnpapa** [comment]
I dont use JSLint. I use JSHint and JSCS. See the .jshintrc and .jscsrc files for those settings.

Use those with webstorm or brackets instead and you wont see those messages
